//!user
export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const GET_USER = "GET_USER";
export const SHOW_USER = "SHOW_USER";
//!art
export const FETCH_ARTS = "FETCH_ARTS";
export const LOADING_ARTS = "LOADING_ARTS";
export const RESET_ALL_LOADED = "RESET_ALL_LOADED";
export const FETCH_ARTS_INF_SCROLL = "FETCH_ARTS_INF_SCROLL";
//!COMMENT
export const CREATE_ART_COMMENT = "CREATE_ART_COMMENT";
export const CREATE_COMMENT_COMMENT = "CREATE_COMMENT_COMMENT";
//!LIKE

export const CREATE_COMMENT_LIKE = "CREATE_COMMENT_LIKE";
export const CREATE_ART_LIKE = "CREATE_ART_LIKE";
export const DESTROY_ART_LIKE = "DESTROY_ART_LIKE";
export const DESTROY_COMMENT_LIKE = "DESTROY_COMMENT_LIKE";


